[package]
name = "agent-design-patterns"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
graph-flow = { version = "0.2.3", features = ["rig"] }
rig-core = "0.15.1"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
